name: workflow-test
on:
  workflow_dispatch:
jobs:
  workflow-test:
    name: Run workflow test
    runs-on: ubuntu-latest
    env:
      GLOBAL: "Global Environment"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with: 
          java-version: '11'
          distribution: 'adopt'
      - name: Setup jq environment
        uses: urgn/setup-jq-action@v3.0.2
      - name: Validate jq version
        run: |
          jq --version
      - name: Validate mvn version
        run: |
          mvn --version
      - name: Test jq feature
        id: user
        run: |
          USER="$(echo '{ "user":"stedolan", "title": "JQ Primer"}' | jq '.user')"
          echo $USER
          echo "::set-output name=user-output::$USER"
      - name: Test if statement
        env:
          USER_OUTPUT: ${{ steps.user.outputs.user-output }}
          LOCAL: "$GLOBAL"
          TEXT: This is an example
        run: |
          if [[ $USER_OUTPUT == '"stedolan"'  ]]
          then
          echo $USER_OUTPUT
          echo $LOCAL
          echo $GLOBAL
          echo $TEXT
          fi
      - name: Run action
        id: run-action
        uses: ./.github/actions/action-test
        with:
          os-name: iOS
      - name: Print result
        env:
          ACTION_OUTPUT: ${{ steps.run-action.outputs.action-output }}
        run: echo $ACTION_OUTPUT
